version: "3.9"

services:
  web:
    build: .
    command: gunicorn myblogsite.wsgi:application --bind 0.0.0.0:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:9000"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    restart: always

volumes:
  static_volume:
