name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: myblogdb
                    POSTGRES_USER: mybloguser
                    POSTGRES_PASSWORD: myblogpass
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            SECRET_KEY: django-insecure-i2io^+f+#=myckn^rq7p=-67-^gi23r&!%6yr#*ok$k(z6i70u
            DEBUG: True
            DB_NAME: myblogdb
            DB_USER: mybloguser
            DB_PASSWORD: myblogpass
            DB_HOST: host.docker.internal
            DB_PORT: 5432
            EMAIL_HOST: smtp.gmail.com
            EMAIL_HOST_USER: matemmix@gmail.com
            EMAIL_HOST_PASSWORD: your_email_app_password
            EMAIL_PORT: 587
            EMAIL_USE_TLS: True
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              run: |
                  python manage.py test
            - name: Run migrations
              run: |
                  python manage.py migrate
